### ISSUE TITLE
429 error while trying to send transaction

### ISSUE THREAD

**Issue by susuper** [MetisProtocol/metis-ansible#1]
Hello.
For more than 8 hours 429 error is returned while trying to send transaction to sequencer:
"429 Too Many Requests Rate Limit Reached"
What is the issue please?

**Comment by susuper** [comment]
> I don't think you will have the 429 error If you just use the rpc to send transactions
You can try by yourself to send the empty tx from any IP:
`curl -X POST --data '{"jsonrpc":"2.0","id":1,"method":"eth_sendRawTransaction"}' -H "Content-Type: application/json" https://andromeda.metis.io`
429 error is returned.

**Comment by ericlee42** [comment]
![image](https://github.com/MetisProtocol/metis-ansible/assets/92196970/9496ed01-b80d-461c-a2ef-d5909f322969)

**Comment by susuper** [comment]
Thank you.
Looks like IPs of major European providers (Vultr, Hetzner) are banned at sequencer's side.
Are there any plans to remove IP ban please?

**Comment by ericlee42** [comment]
We didn't ban any ip addresses.
