### ISSUE TITLE
Cannot sync l1dtl 

### ISSUE THREAD

**Issue by SwatGuard** [MetisProtocol/metis-ansible#6]
Attempting to sync l1dtl always results in this error message:

`{"level":50,"time":1719816403901,"extra":{"message":"Error: failed to meet quorum (method=\"getBlock\", params={\"includeTransactions\":true,\"blockTag\":\"0x11c8afe\"}, results=[{\"weight\":1,\"start\":1719816278847,\"error\":{\"reason\":\"timeout\",\"code\":\"TIMEOUT\",\"requestBody\":\"{\\\"method\\\":\\\"eth_getBlockByNumber\\\",\\\"params\\\":[\\\"0x11c8afe\\\",true],\\\"id\\\":6229417,\\\"jsonrpc\\\":\\\"2.0\\\"}\",\"requestMethod\":\"POST\",\"timeout\":120000,\"url\":\"REDACTED/\"}}], provider={\"_isProvider\":true,\"_events\":[],\"_emitted\":{\"block\":-2},\"formatter\":{\"formats\":{\"transaction\":{},\"transactionRequest\":{},\"receiptLog\":{},\"receipt\":{},\"block\":{},\"blockWithTransactions\":{},\"filter\":{},\"filterLog\":{}}},\"anyNetwork\":false,\"_networkPromise\":{},\"_maxInternalBlockNumber\":20209959,\"_lastBlockNumber\":-2,\"_pollingInterval\":4000,\"_fastQueryDate\":1719816266272,\"providerConfigs\":[{\"priority\":0,\"provider\":{\"_isProvider\":true,\"_events\":[],\"_emitted\":{\"block\":-2},\"formatter\":{\"formats\":{\"transaction\":{},\"transactionRequest\":{},\"receiptLog\":{},\"receipt\":{},\"block\":{},\"blockWithTransactions\":{},\"filter\":{},\"filterLog\":{}}},\"anyNetwork\":false,\"_networkPromise\":{},\"_maxInternalBlockNumber\":20209966,\"_lastBlockNumber\":-2,\"_pollingInterval\":4000,\"_fastQueryDate\":1719816363843,\"connection\":{\"url\":\"REDACTED"},\"_nextId\":6229814,\"_eventLoopCache\":{\"detectNetwork\":null,\"eth_chainId\":null,\"eth_blockNumber\":null},\"_network\":{\"name\":\"homestead\",\"chainId\":1,\"ensAddress\":\"0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e\"},\"_internalBlockNumber\":{},\"_fastBlockNumber\":20209966,\"_fastBlockNumberPromise\":{}},\"stallTimeout\":750,\"weight\":1}],\"quorum\":0.5,\"_highestBlockNumber\":20209959,\"_network\":{\"name\":\"homestead\",\"chainId\":1,\"ensAddress\":\"0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e\"},\"_internalBlockNumber\":{},\"_fastBlockNumber\":20209959,\"_fastBlockNumberPromise\":{}}, code=SERVER_ERROR, version=providers/5.4.4)","stack":"/opt/optimism/node_modules/ethers/node_modules/@ethersproject/providers/node_modules/@ethersproject/logger/src.ts/index.ts:225\n        const error: any = new Error(message);\n                           ^\n\nError: failed to meet quorum (method=\"getBlock\", params={\"includeTransactions\":true,\"blockTag\":\"0x11c8afe\"}, results=[{\"weight\":1,\"start\":1719816278847,\"error\":{\"reason\":\"timeout\",\"code\":\"TIMEOUT\",\"requestBody\":\"{\\\"method\\\":\\\"eth_getBlockByNumber\\\",\\\"params\\\":[\\\"0x11c8afe\\\",true],\\\"id\\\":6229417,\\\"jsonrpc\\\":\\\"2.0\\\"}\",\"requestMethod\":\"POST\",\"timeout\":120000,\"url\":\"REDACTED"}}], provider={\"_isProvider\":true,\"_events\":[],\"_emitted\":{\"block\":-2},\"formatter\":{\"formats\":{\"transaction\":{},\"transactionRequest\":{},\"receiptLog\":{},\"receipt\":{},\"block\":{},\"blockWithTransactions\":{},\"filter\":{},\"filterLog\":{}}},\"anyNetwork\":false,\"_networkPromise\":{},\"_maxInternalBlockNumber\":20209959,\"_lastBlockNumber\":-2,\"_pollingInterval\":4000,\"_fastQueryDate\":1719816266272,\"providerConfigs\":[{\"priority\":0,\"provider\":{\"_isProvider\":true,\"_events\":[],\"_emitted\":{\"block\":-2},\"formatter\":{\"formats\":{\"transaction\":{},\"transactionRequest\":{},\"receiptLog\":{},\"receipt\":{},\"block\":{},\"blockWithTransactions\":{},\"filter\":{},\"filterLog\":{}}},\"anyNetwork\":false,\"_networkPromise\":{},\"_maxInternalBlockNumber\":20209966,\"_lastBlockNumber\":-2,\"_pollingInterval\":4000,\"_fastQueryDate\":1719816363843,\"connection\":{\"url\":\"REDACTED"},\"_nextId\":6229814,\"_eventLoopCache\":{\"detectNetwork\":null,\"eth_chainId\":null,\"eth_blockNumber\":null},\"_network\":{\"name\":\"homestead\",\"chainId\":1,\"ensAddress\":\"0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e\"},\"_internalBlockNumber\":{},\"_fastBlockNumber\":20209966,\"_fastBlockNumberPromise\":{}},\"stallTimeout\":750,\"weight\":1}],\"quorum\":0.5,\"_highestBlockNumber\":20209959,\"_network\":{\"name\":\"homestead\",\"chainId\":1,\"ensAddress\":\"0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e\"},\"_internalBlockNumber\":{},\"_fastBlockNumber\":20209959,\"_fastBlockNumberPromise\":{}}, code=SERVER_ERROR, version=providers/5.4.4)\n    at Logger.Logger.makeError (/opt/optimism/node_modules/ethers/node_modules/@ethersproject/providers/node_modules/@ethersproject/logger/src.ts/index.ts:225:28)\n    at Logger.Logger.throwError (/opt/optimism/node_modules/ethers/node_modules/@ethersproject/providers/node_modules/@ethersproject/logger/src.ts/index.ts:237:20)\n    at FallbackProvider.<anonymous> (/opt/optimism/node_modules/ethers/node_modules/@ethersproject/providers/src.ts/fallback-provider.ts:644:23)\n    at step (/opt/optimism/node_modules/ethers/node_modules/@ethersproject/providers/src.ts/fallback-provider.ts:1:14)\n    at Object.next (/opt/optimism/node_modules/ethers/node_modules/@ethersproject/providers/src.ts/fallback-provider.ts:1:14)\n    at fulfilled (/opt/optimism/node_modules/ethers/node_modules/@ethersproject/providers/src.ts/fallback-provider.ts:1:14)\n    at runMicrotasks (<anonymous>)\n    at runNextTicks (node:internal/process/task_queues:61:5)\n    at listOnTimeout (node:internal/timers:528:9)\n    at processTimers (node:internal/timers:502:7)","code":"SERVER_ERROR"},"msg":"Caught an unhandled error"}`

Running the latest docker compose with metisdao/dtl:v0.1.2  
Also running with DATA_TRANSPORT_LAYER__SYNC_L1_BATCH=true

I usually see this message around block 18574677 - 18647859 - L1 blocks. After this it just stops syncing.

**Comment by ericlee42** [comment]
> "error\":{\"reason\":\"timeout\",\"code\":\"TIMEOUT\"

It's the timeout error.

Please check if your rpc is healthy and working.
