### ISSUE TITLE
Node syncing l2geth from 0, stuck at block 15214538

### ISSUE THREAD

**Issue by COLUD4** [MetisProtocol/metis-ansible#7]
INFO [07-04|06:16:15.665] sync from other node applyTransactionToTip finish current latest=15214537
ERROR[07-04|06:16:15.840] handler blocksBeforeInsert get equeue err="element not found"
WARN [07-04|06:16:15.840] Synchronisation failed, retrying err="element not found"
ERROR[07-04|06:16:33.327] handler blocksBeforeInsert get equeue err="element not found"
WARN [07-04|06:16:33.327] Synchronisation failed, retrying err="element not found"

The node information is
metisdao/dtl:v0.1.2
metisdao/l2geth:v0.2.4
https://github.com/MetisProtocol/metis-ansible/blob/main/playbooks/files/andromeda/l1dtl.env
DATA_TRANSPORT_LAYER__SYNC_L1_BATCH=true

https://github.com/MetisProtocol/metis-ansible/blob/main/playbooks/files/andromeda/l2geth.env

**Comment by ericlee42** [comment]
It means your l1dtl is syncing, you can just wait for its complete.
